apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
data:
  schema-version: v2
  config-version: ahmk8s1
  controlplane-metrics: |-
    default-targets-scrape-enabled: |-
      node-auto-provisioning = true
