apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
data:
  prometheus-config: |-
    scrape_configs:
      - job_name: aks-istio-ingressgateway-external
        scheme: http
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - aks-istio-ingress
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_label_istio
            action: keep
            regex: aks-istio-ingressgateway-external
          - source_labels:
              - __meta_kubernetes_pod_phase
            action: keep
            regex: Running
          - source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__
            replacement: $1:15090
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
        metric_relabel_configs:
          - source_labels:
              - __name__
            action: keep
            regex: istio_.*
